name: 🐛 Bug Report
description: Report a bug in SelfCoE
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug in SelfCoE! Please fill out the form below to help us understand and fix the issue.

  - type: checkboxes
    id: environment
    attributes:
      label: Environment
      description: What environment are you running SelfCoE in?
      options:
        - label: Development (yarn start)
        - label: Production deployment
        - label: Docker container
        - label: Kubernetes cluster

  - type: input
    id: version
    attributes:
      label: SelfCoE Version
      description: What version of SelfCoE are you running?
      placeholder: "v1.0.0 or commit hash"
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: "v20.19.4"
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: What browser are you using (if frontend issue)?
      placeholder: "Chrome 138.0.0.0"

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: "Describe the bug..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: "I expected..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: "Instead, what happened was..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Any relevant log output (console errors, server logs, etc.)
      placeholder: "Paste logs here..."
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Frontend (React app)
        - Backend (Node.js API)
        - Database
        - Authentication
        - Catalog
        - Scaffolder
        - Search
        - TechDocs
        - Plugins
        - Configuration
        - Other

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have provided all the required information above
          required: true
        - label: I have tested this on the latest version of SelfCoE
          required: true