name: 📚 Documentation Issue
description: Report an issue with documentation or request documentation improvements
title: "[Docs]: "
labels: ["documentation"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve SelfCoE documentation! Please fill out the form below.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing Documentation
        - Incorrect Documentation
        - Outdated Documentation
        - Unclear Documentation
        - Documentation Improvement
        - New Documentation Request
    validations:
      required: true

  - type: dropdown
    id: doc-section
    attributes:
      label: Documentation Section
      description: Which section of documentation is affected?
      options:
        - README
        - Getting Started Guide
        - Installation Instructions
        - Configuration Guide
        - API Documentation
        - Plugin Documentation
        - Troubleshooting
        - Contributing Guidelines
        - Deployment Guide
        - Developer Guide
        - User Guide
        - Other
    validations:
      required: true

  - type: input
    id: doc-url
    attributes:
      label: Documentation URL
      description: Link to the specific documentation page (if applicable)
      placeholder: "https://larralapid.github.io/SelfCoE/..."

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Clearly describe the documentation issue
      placeholder: "The documentation is missing information about..."
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: What does the documentation currently say? (copy/paste if needed)
      placeholder: "Currently, the documentation says..."

  - type: textarea
    id: suggested-content
    attributes:
      label: Suggested Content
      description: What should the documentation say instead?
      placeholder: "It should say..."

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional context that would help improve the documentation
      placeholder: "This would help users who..."

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who is the primary audience for this documentation?
      options:
        - End Users
        - Developers
        - System Administrators
        - Contributors
        - New Users
        - Advanced Users
        - All Users

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this documentation fix?
      options:
        - Low - Minor improvement
        - Medium - Affects user experience
        - High - Important for adoption
        - Critical - Blocking usage
    validations:
      required: true

  - type: checkboxes
    id: doc-format
    attributes:
      label: Documentation Format
      description: What format should this documentation be in?
      options:
        - Markdown (.md files)
        - GitHub Pages
        - Code comments
        - API documentation
        - Video/Screenshots
        - Examples/Tutorials

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help improve this documentation?
      options:
        - label: I can help write the documentation
        - label: I can review documentation changes
        - label: I can provide examples or screenshots
        - label: I can test the documentation accuracy

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to make sure this isn't a duplicate
          required: true
        - label: I have provided specific information about the documentation issue
          required: true
        - label: I have checked the latest version of the documentation
          required: true